### ISSUE TITLE
Несколько хотелок

### ISSUE THREAD

**Issue by zorn-v** [KonishchevDmitry/binup#1]
В чем смысл в 2 разных субкоммандах install/upgrade ?
Как я вижу - просто запустил `binup` и он с конфига все автоматически обновляет и/или устанавливает, если бинарника нет на месте.
Можно еще сделать чтобы опционально можно было обновлять только определенные бинарники например 
`binup binup`

Так же было бы удобно добавлять в конфиг новые записи через cli
Например
`binup --add binup:KonishchevDmitry/binup`
добавляет в раздел tools
```yaml
    binup:
        project: KonishchevDmitry/binup
```

Ну и до кучи `binup --remove binup` :smile: 
Можно с доп параметром, чтобы с диска бинарник тоже удалял. 
Ну или спрашивал интерактивно.

И получится такой маленький пакетный манагер :smile:

**Comment by KonishchevDmitry** [comment]
> В чем смысл в 2 разных субкоммандах install/upgrade ?

Ну, не всегда нужно именно обновляться до последней версии – иногда хочется просто сказать "убедись, что установлено всё, что описано в конфиге". К примеру, я свою VPS'ку конфигурю через Ansible, и мне там не нужно, чтобы на каждом прогоне она пыталась обновить установленные приложения – а скорее, также как и с apt-модулем, хочется только устанавливать, если оно ещё не установлено.

> Можно еще сделать чтобы опционально можно было обновлять только определенные бинарники

Это работает уже сейчас – `binup upgrade binup`

> Так же было бы удобно добавлять в конфиг новые записи через cli

Да, спасибо – тоже думал об этом. Мне оно пока не нужно, но если будет спрос, то для удобства определённо имеет смысл сделать. Надо только найти библиотечку, которая умеет править yaml-файлы, сохраняя разметку и комментарии. :)

**Comment by zorn-v** [comment]
> Ну, не всегда нужно именно обновляться до последней версии – иногда хочется просто сказать "убедись, что установлено всё, что описано в конфиге"

Аргумент. Но для часто используемой опции должно быть что то, что быстро набирается. 
Например действие upgrade если запустил без параметров.
Если первый раз запускаешь все равно в конфиге ничего нет.

**Comment by zorn-v** [comment]
Как вариант если нет конфига выводит хелп

**Comment by KonishchevDmitry** [comment]
Пошёл сейчас посмотреть, чем можно было бы редактировать конфиг – пока нашёл только https://github.com/udoprog/nondestructive

И сразу же нашёл в нем пару багов. Сделал туда PR – https://github.com/udoprog/nondestructive/pull/16 Если вмержат, то кажется можно попробовать на базе него сделать.

**Comment by KonishchevDmitry** [comment]
Добавил автоматическую правку конфига + короткие алиасы на команды.
